recipes-browser/wpewebkit/wpewebkit/fix_API_JSStringRef_type_conversion.patch
recipes-browser/wpewebkit/wpewebkit/fix_JSStringRef_type_conversion.patch
recipes-browser/wpewebkit/wpewebkit/fix_WKString_type_conversion.patch
recipes-browser/wpewebkit/wpewebkit/fix_WebEventFactory.patch
recipes-browser/wpewebkit/wpewebkit_git.bb

```
error: invalid conversion from ‘const UChar* {aka const char16_t*}’ to ‘const JSChar* {aka const short unsigned int*}’ [-fpermissive]
```
The patch is based on the original bugfix for webkitgtk on Gentoo: https://bugs.gentoo.org/621532
Status: **WIP**
* This patch is tested in a `rocko` naive environment
* ~~TODO: test if also works in `pyro`~~ **Tested**
Signed-off-by: Pablo Saavedra <psaavedra at igalia.com>

WIP: Fix JSStringRef_type_conversion error compiling with gcc7

---

recipes-browser/webkitgtk/webkitgtk_2.20.3.bb

Latest stable released on 2018-06-11
Changes: https://www.webkitgtk.org/2018/06/11/webkitgtk2.20.3-released.html

webkitgtk: upgrade to 2.20.3

---

recipes-browser/images/core-image-wpe-crosscompilation.bb

Add the core-image-wpe-crosscompilation recipe that can be used to generate
a minimal wpewebkit build that can then be used for cross-compilation by
generating the SDK for this image and using it with WebKit ToT builds.

Add core-image-wpe-crosscompilation recipe

---

recipes-browser/cog/cog.inc
recipes-browser/cog/cog_0.1.0.bb
recipes-browser/cog/cog_git.bb
recipes-browser/wpebackend-fdo/wpebackend-fdo_0.1~git0.2.bb
recipes-browser/wpewebkit/wpewebkit/fix-189500.patch
recipes-browser/wpewebkit/wpewebkit/fix-189506.patch
recipes-browser/wpewebkit/wpewebkit/fix-189540.patch
recipes-browser/wpewebkit/wpewebkit_2.21.91.bb

* Create recipe for cog_0.1 compatible
* Add upstreamed patches for wpewebkit_2.21.91 needed to build package
* Add support for building on older versions of wayland and EGL in WPEBackend-fdo (0.1~git0.2)

Fixes for wpewebkit_2.21.91, new cog 0.1 and new WPEBackend-fdo (0.1~git0.2)

---

recipes-browser/wpebackend-fdo/wpebackend-fdo.inc

FILES_SOLIBSDEV="" forces all libraries (versioned and unversioned)
to be included in the wpebackend-fdo package.
Related with: https://github.com/Igalia/meta-webkit/pull/27#discussion_r216009124

Set FILES_SOLIBSDEV="" in wpebackend-fdo

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_git.bb

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
When trying to build wpebackend-fdo from git with the recent WPEwebkit (2.22.0),
the build fails at `package wpewebkit-2.22.0-r0.armv7vet2hf_neon conflicts with wpebackend-fdo < 1.0 provided by libwpebackend-fdo-0.1-1-1.0~git-r0.armv7vehf_neon`
Apparently, the build systems consider the version `1.0~git` to be lower that `1.0`. Changing
it to `1.0.0~git` allows the build to pass.

wpebackend-fdo_git.bb: set PV to 1.0.0~git

---

recipes-browser/wpewebkit/wpewebkit.inc

Since GStreamer 1.14 the gst-gl library is part of -base.

wpewebkit: Switch gst-gl dependency to gst-plugins-base

---

recipes-browser/wpewebkit/wpewebkit.inc

This options enables the libwebrtc support of WPE. It is disabled by default,
for now.

wpewebkit: New config option for WebRTC support

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_0.1.bb
recipes-browser/wpebackend-fdo/wpebackend-fdo_0.1~git0.2.bb

* wpebackend-fdo 0.1 version is used by wpewebkit 2.20 version.
* Note: This is will not the case of the libwpe package. Since WPE 2.22.x,
it won't be needed anymore (https://github.com/Igalia/cog/pull/60),
it is recommended to set the implementation library name using the
libwpe API like this instead of having the ugly symlink.

fix: wpebackend-fdo 0.1 version still needs libWPEBackend-default symlink

---

.gitlab-ci.yml
recipes-browser/cog/cog_0.1.1.bb
recipes-browser/cog/cog_0.2.0.bb
recipes-browser/libwpe/libwpe.inc
recipes-browser/wpebackend-rdk/wpebackend-rdk.inc
recipes-browser/wpebackend-rdk/wpebackend-rdk/0001-Fix-include-of-headers-after-WPEBackend-commit-2bf3c.patch
recipes-browser/wpebackend-rdk/wpebackend-rdk/0001-WPEBackend-libraries-are-versioned-now.patch
recipes-browser/wpebackend-rdk/wpebackend-rdk_1.20180411.bb
recipes-browser/wpebackend-rdk/wpebackend-rdk_1.20180925.bb
recipes-browser/wpebackend/wpebackend.inc
recipes-browser/wpewebkit/wpewebkit.inc
recipes-browser/wpewebkit/wpewebkit_2.20.2.bb

* cog:
* Added cog 0.2.0 recipe based on tarball release.
* Added run conflict with wpewebkit (>= 2.21) in cog-0.1.1
* Added run conflict with wpebackend-rdk (> 1.20180411) in cog-0.20.2
* virtual/libwpe:
* libwpe provides virtual/libwpe
* wpebackend also provides virtual/libwpe
* wpebackend-rdk:
* Restored wpebackend-rdk (1.20180411). Still needed to build the
wpewebkit-2.20.2 recipe:
commit 2b4ea01
Author: Zan Dobersek <zdobersek@igalia.com>
Date:   Fri Sep 28 08:29:54 2018 +0200
wpebackend-rdk: bump the version, fix deps, remove
unnecessary patches.
* Common definitions isolated in wpebackend-rdk.inc
* wpebackend-rdk-git remamed to 1.20180925
* New wpebackend-rdk-git points to the master HEAD

Various changes in the recipes 

---

recipes-browser/cog/cog_0.2.0.bb
recipes-browser/cog/cog_git.bb

By default cog_git would be selected to be used but that does not work as its Version 0.3.0 which depends on wpewebkit 2.24 but only 2.22 is available in sumo.
Cog 0.2.0 on the other hand works with wepewebkit 2.22.
The recipe is copied from master

add recipe for cog 0.2.0 and make it default

---

.gitlab-ci.yml
recipes-browser/wpewebkit/wpewebkit_2.24.1.bb

```
WPE WebKit 2.24.1 is available for download at:
https://wpewebkit.org/releases/wpewebkit-2.24.1.tar.xz (16.1MB)
md5sum: 0f7b792874853416d8005b020bd90685
sha1sum: d009c82afbc2c373a7f34ffda392e5c3b52dac7d
sha256sum: 95f2fb68429fbd901ea415d09fdd88d6d9ac5ec2d170bec9977093b12e5093a6
This is the first bug fix release in the stable 2.24 series.
What's new in the WPE WebKit 2.24.1 release?
============================================
- Do not allow changes in active URI before provisional load starts for non-API requests.
- Stop the threaded compositor when the page is not visible or layer tree state is frozen.
- Use WebKit HTTP source element again for adaptive streaming fragments downloading.
- Properly handle empty resources in webkit_web_resource_get_data().
- Add quirk to ensure …
```

[wpe-webkit] Bumping up WPE WebKit to 2.24.1 (refs: #94)

---

recipes-browser/wpewebkit/wpewebkit.inc

Also remove the dependency on souphttpsrc because we now use WebKit for all HTTP
media traffic. Not depending on -bad will allow meta-gstreamer1.0 to enable its
GstWPE plugin, otherwise we would have a dependency loop.

wpewebkit: Break the direct dependency to gst-plugins-bad

---

recipes-browser/cog/cog.inc

In the upcoming Cog 0.4.0 wayland-scanner is build-time requirement.

recipes-browser: cog: Add build dependency to Wayland

---

recipes-browser/cog/cog_git.bb

Building the bleeding edge version of cog by default is problematic for
creating stable builds. Prefer the stable released versions instead.

cog: Don't build bleeding edge version by default

---

recipes-browser/cog/cog.inc

cog depends on wayland and wayland-native when is built with FDO

cog: required wayland dependencies when fdo

---

recipes-browser/wpewebkit/wpewebkit.inc
recipes-browser/wpewebkit/wpewebkit_trunk.bb

Add ENABLE_UNIFIED_BUILDS option to cmake ports is available since r239561 in WebKit. WebKit 2.24 begins in 241291 so this cmake flag is available for WebKit 2.24 and higher.
* git-svn-id: http://svn.webkit.org/repository/webkit/trunk@239561
* git-svn-id: http://svn.webkit.org/repository/webkit/trunk@241291
wpewebkit: bump trunk version (r244225)
WebKit should build successfully even with -DENABLE_UNIFIED_BUILDS=OFF
https://bugs.webkit.org/show_bug.cgi?id=196845

wpewebkit: Add unified-builds PACKAGECONFIG

---

.gitlab-ci.yml
recipes-browser/wpewebkit/wpewebkit_2.26.2.bb

* Bumping up WPE WebKit to 2.26.2:
- Improve performance of querying system fallback fonts.
- Don't use prgname in dbus-proxy socket path.
- Fix thread-safety issues in image decoders.
- Fix the build with WebDriver disabled.
- Fix several crashes and rendering issues.
- Ref: https://lists.webkit.org/pipermail/webkit-wpe/2019-November/000287.html
* Added missing CI task for 2.26.X

wpewebkit: bumping up WPE WebKit to 2.26.2

---

recipes-browser/wpewebkit/wpewebkit.inc

oe-core will correctly configure cmake to use ccache based on the CCACHE
bitbake variable, so don't set it explicitly in the wpewebkit recipe.
Setting it explicitly causes issues if a user doesn't want to use ccache
for some reason (for example, if they are using icecream instead).
If using ccache for this specific recipe is desired, one can set the
following in local.conf:
CCACHE_pn-wpewebkit = "ccache"
Signed-off-by: Joshua Watt <Joshua.Watt@garmin.com>

wpewebkit: Fix ccache usage

---

recipes-flatpak/bubblewrap/bubblewrap_0.3.1.bb
recipes-flatpak/xdg-dbus-proxy/xdg-dbus-proxy_0.1.0.bb

Fixes
ERROR: QA Issue: bubblewrap: SRC_URI uses PN not BPN [src-uri-bad]

bubblewrap,xdg-dbus-proxy: Update SRC_URI to change BPN instead of PN

---

recipes-browser/wpewebkit/wpewebkit.inc

mips binutils started to support .gnu_hash but gold linker is not there yet

wpewebkit: Do not use gold linker on mips

---

recipes-browser/webkitgtk/webkitgtk.inc

webkitgtk does now seem to support the new version.
old enchant 1.x version is gone from oe-core

webkitgtk: Use enchant2 instead of enchant

---

recipes-benchmark/browserperfrunner/browserperfrunner_git.bb

* browserperfrunner its still not python3 ready, so we raise and
error telling to use meta-python2 if someone tries to build it on
yocto dunfell or newer.
* the inherit call to python-dir its done conditionally to avoid
raising a parse error when this bbclass its not found.
See also: #150

Make browserperfrunner depend on meta-python2 on yocto >= dunfell

---

README.md
conf/layer.conf
recipes-benchmark/browserperfrunner/browserperfrunner_git.bb
recipes-browser/images/core-image-wpe-crosscompilation.bb
recipes-browser/webkitgtk/webkitgtk_2.28.0.bb

Added a conditional inherit of distro_features_check for old releases. The distro_features_check is going to be removed after dunfell. 
Ref:
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/meta/classes/features_check.bbclass?h=master-next&id=9702544b3e75d761d86cae7e8b36f3f2625b68ce
Also, updated the layer compatibility to: `warrior zeus dunfell`

Fix the meta-webkit layer for old poky releases oder than dunfell.

---

dynamic-layers/qt5-layer/recipes-browser/wpewebkit/wpewebkit_%.bbappend
recipes-browser/wpewebkit/wpewebkit.inc

Leave this choice to user, since meta-qt5 maybe includes in layermix for
other reasons.

wpewebkit: Do not enable qtwpe packageconfig automatically with meta-qt5

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_1.6.0.bb

* Use libepoxy for EGL operations
```
Instead of relying on EGL headers and library provided at compile-time, use libepoxy to push that necessity to runtime.
The CMake integration follows the new 'imported' model. Instead of manually parsing the EGL extension list to detect present extensions, we can rely on the epoxy_has_egl_extension() function.
```
Package reference:
https://github.com/Igalia/WPEBackend-fdo/commit/69d8aa3c40f71994a6e41d5769807a7bbf6725dc

wpebackend-fdo: wpebackend-fdo >= 1.8 depends on libepoxy

---

recipes-browser/webkitgtk/webkitgtk_2.28.1.bb

Several vulnerabilities were discovered in WebKitGTK and WPE WebKit.
```
CVE-2020-11793
Versions affected: WebKitGTK before 2.28.1 and WPE WebKit before
2.28.1.
Credit to Cim Stordal of Cognite.
Impact: Processing maliciously crafted web content may lead to
arbitrary code execution or application crash (denial of service).
Description: A memory corruption issue (use-after-free) was
addressed with improved memory handling.
```

webkitgtk: upgrade to 2.28.1

---

recipes-browser/wpewebkit/wpewebkit.inc

This fixes linker errors eg.
Source/WTF/wtf/CMakeFiles/WTF.dir/Assertions.cpp.o:Assertions.cpp:(.text+
0x4c8): more undefined references to `__atomic_compare_exchange_1' follow
| collect2: error: ld returned 1 exit status
| [2268/4244] Linking CXX executable bin/LLIntOffsetsExtractor
| ninja: build stopped: subcommand failed.

wpewebkit: Fix linker errors on riscv64

---

recipes-browser/wpewebkit/wpewebkit.inc

There were issues with clang-6 but now a days we are using clang-10 in
meta-clang and that can happily compile wpewebkit ( infact faster )

wpewebkit: Do not pin to gcc-only compiler

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_1.6.1.bb

* Fixed build when using EGL stacks with odd EGLNativeDisplay definitions.
* Fixed version retrieval functions not being exposed as public symbols.
* Improve build configuration by instructing CMake to report mismatched versions of dependency libraries, instead of failing to compile.

wpebackend-fdo: Update to 1.6.1

---

classes/ruby.bbclass
recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bb
recipes-devtools/dicts/test-dicts_git.bb
recipes-devtools/fonts/webkit-test-fonts_git.bb
recipes-devtools/ruby/ruby-highline/fix-spec-files.patch
recipes-devtools/ruby/ruby-highline_git.bb
recipes-devtools/ruby/ruby-json_1.8.6.bb

* Add packagegroup-wpewebkit-depends. Need to build images and toolchains with all the dependencies to build or run WebKit but without WebKit
* wpewebkit: bumb trunk version (compatible with wpe-1.0)
* Add required recipes to build to run the WebKit Layout tests
* ~~reverted a patch in Ruby recipe. This is needed to build the Ruby packages from meta-cloud-services/meta-openstack~~
* added json and highline ruby packages
* added mrobinson's dicts and fonts resources

Required recipes to build images and toolchains to build WPE

---

recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bb

This helps in making sure musl based distros can safely parse recipes
from meta-webkit

packagegroup-wpewebkit-depends: Separate out libc specific dependencies

---

recipes-browser/wpebackend-fdo/wpebackend-fdo.inc

Libs like libwayland-egl should be provided by packages supporting this virtual package (usually mesa but it could be any other). This library is normally used for Wayland apps such Weston for stacked Weston servers and so.
In the top of that, for the case of the wpebackend-fdo makes all the sense this dependency because this package indeed relies on the FDO stack.

wpebackend-fdo: Add virtual/mesa as dependency

---

recipes-browser/webkitgtk/webkitgtk_2.30.3.bb

Release notes:
* https://webkitgtk.org/2020/11/20/webkitgtk2.30.3-released.html
* https://webkitgtk.org/2020/10/23/webkitgtk2.30.2-released.html
* https://webkitgtk.org/2020/09/21/webkitgtk2.30.1-released.html

webkitgtk: Bump up webkitgtk to 2.30.3

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_1.8.0.bb

These dependencies are needed since wpebackend-fdo>=1.8.X
Unreviewed patch.

wpebackend-fdo: Update dependencies

---

recipes-browser/wpebackend-fdo/wpebackend-fdo.inc

wpebackend-fdo uses meson since (not branched yet):
Ref:
https://github.com/Igalia/WPEBackend-fdo/commit/9c13d73bcc3726e2290c182d76d67b384f4c1318
Unreviewed patch.

wpebackend-fdo: Inherit from meson

---

recipes-browser/wpebackend-fdo/wpebackend-fdo.inc
recipes-browser/wpebackend-fdo/wpebackend-fdo_1.6.1.bb
recipes-browser/wpebackend-fdo/wpebackend-fdo_1.8.0.bb
recipes-browser/wpebackend-fdo/wpebackend-fdo_devupstream.bb

We can not use SRCREV to discern for what version is being processed in the bitbake execution to chose what class inherit. For example:
inherit ${@bb.utils.contains("SRCREV", 'INVALID', 'cmake', 'meson', d)}
That line is not valid because d.getVar(d, "SRCREV") is evaluated always to INVALID in this stage.
This patch moves the class-devupstream customizations to a new recipe (wpebackend-fdo_devupstream.bb). In addition, the 'inherit' statement is explicitly declared in each recipe.
This fix the regression introduced in 2665a3d557b3c12b891898eb412545ee63aff273 building the bleeding-edge version.
Unreviewed patch.

wpebackend-fdo: Create wpebackend-fdo_devupstream

---

recipes-browser/webkitgtk/webkitgtk_2.30.5.bb

Release notes:
* https://webkitgtk.org/2021/02/11/webkitgtk2.30.5-released.html

webkitgtk: Bump up webkitgtk to 2.30.5

---

recipes-browser/webkitgtk/webkitgtk_2.30.5.bb

Fixes:
* webkitgtk: Remove unused features_check
* webkitgtk: Fix recipe webkitgtk sets S variable with trailing slash
Related to https://github.com/Igalia/meta-webkit/issues/211

Fix several warnings in the webkitgtk_2.30.X in gatesgarth #211

---

recipes-browser/cog/cog.inc

This is specially useful when the recipe is configured to enable system dbus
session support.

cog: Allow dbus owner user configuration

---

recipes-browser/wpewebkit/wpewebkit/274943-GStreamer-Use-imxvideoconvert_g2d-element-inside-the.patch
recipes-browser/wpewebkit/wpewebkit_2.30.6.bb
recipes-browser/wpewebkit/wpewebkit_2.31.91.bb

Provide and apply the upstream r274943 patch on top of the currently-used
2.30 and 2.32 releases.
This patch adjusts the GStreamer sink creation by including the
imxvideoconvert_g2d element at the beginning of the sink if it's found to be
present on the system. This converter element is needed on some iMX platforms
(generally the ones it's provided on) to perform additional conversion passes
to make the visual output presentable in our pipeline.
It's not a given that the patch will be merged into the 2.30 stable series,
hence it's being added here. It will be included in the next unstable release
so it should be removable whenever the 2.32 version is updated.

wpewebkit: apply upstream r274943 patch for the 2.30 and 2.32 releases

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_devupstream.bb

It's a git checkout, so the source directory has to be adjusted accordingly. Otherwise, an error pops up during the license validation since the COPYING file isn't found.

wpebackend-fdo: adjust the source directory for the devupstream version.

---

recipes-browser/wpewebkit/wpewebkit.inc

Make wpewebkit compatible with ccache enabled in local.conf:
INHERIT += "ccache"
Fixes the ccache error:
ccache: error: Recursive invocation (the name of the ccache binary must be "ccache")
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

wpewebkit: make it compatible with yocto ccache

---

recipes-browser/webkitgtk/webkitgtk_2.32.0.bb

Fixes build when systemd or gamepad is not used

webkitgtk: Add packageconfigs for gamepad and systemd

---

recipes-browser/webkitgtk/webkitgtk/musl.patch
recipes-browser/webkitgtk/webkitgtk_2.32.0.bb
recipes-browser/wpewebkit/wpewebkit/musl.patch
recipes-browser/wpewebkit/wpewebkit_2.32.0.bb

Adjust jsc maximum stack limits, so we can avoid stack overflows while
executing javascript code

wpewebkit: Fix build with musl

---

dynamic-layers/qt5-layer/recipes-qt/qt-wpe-simple-browser/qt-wpe-simple-browser_0.1.bb

This PR cleanup the deps so all Yocto mechanisms are working correctly.

qt-wpe-simple-browser: fix runtime and build dependencies

---

recipes-browser/wpewebkit/wpewebkit.inc

libgles2 is a runtime dependency of wpewebkit.  Currently libgles2 is
specified as a dependency, but the library isn't directly linked against
by wpewebkit.  This is because wpewebkit uses libepoxy, which loads
libgles2 via dlopen.
Since libgles2 is a runtime dependency of wpewebkit, even though it is
not directly linked against, it is now listed in RDEPENDS.
Signed-off-by: Colin McAllister <colin.mcallister@garmin.com>

wpewebkit: Add libgles2 to runtime dependencies

---

recipes-browser/cog/cog.inc

Add the D-Bus policy configuration file into the list of files that should be included in the resulting cog package.
Fixes this QA issue with dbus packageconfig:
```
ERROR: cog-0.10.0-r0 do_package: QA Issue: cog: Files/directories were installed but not shipped in any package:
/usr/share/dbus-1
/usr/share/dbus-1/system.d
/usr/share/dbus-1/system.d/com.igalia.Cog.conf
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
cog: 3 installed and not shipped files. [installed-vs-shipped]
ERROR: cog-0.10.0-r0 do_package: Fatal QA errors found, failing task.
```

cog: add D-Bus policy configuration to FILES_${PN} to fix QA issue

---

recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bb

strace is not ported to rv32 yet

packagegroup-wpewebkit-depends: Remove strace on riscv32

---

recipes-browser/cog/cog.inc
recipes-browser/cog/cog_0.8.1.bb

Pulled in chagnes to cog 0.8.1 recipe in main to fix SRC_URI for cog 0.8.1.
Signed-off-by: Colin McAllister <colin.mcallister@garmin.com>

cog: Fix SRC_URI for cog 0.8.1

---

recipes-cdm/sparkle-cdm/sparkle-cdm_git.bb

This new version includes a generic decryptor and a basic player demonstrating
how to use it for encrypted DASH playback.

sparkle-cdm: Bump to latest git snapshot

---

recipes-browser/webkitgtk/webkitgtk_2.32.3.bb
recipes-browser/wpewebkit/wpewebkit_2.32.3.bb

Release notes: https://wpewebkit.org/release/wpewebkit-2.32.3.html
* Properly set the cookies settings after a network process crash.
* Fix accessibility tree after a cross site navigation with PSON enabled.
* Ensure WebKitScriptWorld::window-object-cleared signal is always emitted.
Release notes: https://wpewebkit.org/release/wpewebkit-2.32.2.html
* Improve the touch gesture touch controller.
* Fix handling of wheel events for devices which produce axis events.
* Fix kinetic scrolling on touchpad with async scrolling off.
* Fix a crash on empty drag operation in X11.
* Handle null native surface for for surfaceless rendering.
* Fix JavaScriptCore crash on 32-bit big endian systems.

wpewebkit: Bump up version to 2.32.3

---

recipes-browser/webkitgtk/webkitgtk_2.32.4.bb
recipes-browser/wpewebkit/wpewebkit_2.32.4.bb

* Do not append .asc extension to downloaded text/plain files.
* Fix several crashes and rendering issues
Security Advisory:
* Several vulnerabilities were discovered in WebKitGTK and WPE WebKit.
* https://webkitgtk.org/security/WSA-2021-0005.html
CVE-2021-30858
Versions affected: WebKitGTK and WPE WebKit before 2.32.4.
Credit to an anonymous researcher.
Impact: Processing maliciously crafted web content may lead to
arbitrary code execution. Apple is aware of a report that this issue
may have been actively exploited. Description: A use after free
issue was addressed with improved memory management.

webkitgtk,wpewebkit: Bump up version to 2.32.4

---

recipes-browser/wpewebkit/wpewebkit/0002-libyuv-gcc-issue.patch
recipes-browser/wpewebkit/wpewebkit_2.34.1.bb

When building the wpewebkit from the git-source together with libwebrtc for imx8 there is a compiling Issue within libyuv. This is already fixed, but not in the currently used version. I created a patch for it.
Please have a look here:
https://chromium-review.googlesource.com/c/libyuv/libyuv/+/2922146
and here:
https://chromium-review.googlesource.com/c/libyuv/libyuv/+/2922147

Fix compiler issue with the libyuv library in libwebrtc

---

recipes-browser/wpewebkit/wpewebkit_2.34.2.bb

The new syntax was introduced in #308.
Fixes: #332

wpewebkit: fix override syntax for SRC_URI

---

recipes-browser/webkitgtk/webkitgtk_2.34.3.bb
recipes-browser/wpewebkit/wpewebkit_2.34.3.bb

This is a bug fix release in the stable 2.34 series.
Release notes:
* Make audio tools (like mixers) display the actual name of the application
producing sound, instead of a generic one.
Ref:
* https://webkitgtk.org/2021/12/20/webkitgtk2.34.3-released.html
* https://wpewebkit.org/release/wpewebkit-2.34.3.html

webkitgtk,wpewebkit: bump to version 2.34.3

---

recipes-browser/webkitgtk/webkitgtk_2.34.4.bb
recipes-browser/wpewebkit/wpewebkit_2.34.4.bb

```
webkitgtk: bump to version 2.34.4
This is a bug fix release in the stable 2.34 series.
Release notes:
Ref: https://webkitgtk.org/2022/01/21/webkitgtk2.34.4-released.html
```
```
wpewebkit: bump to version 2.34.4
This is a bug fix release in the stable 2.34 series.
Release notes:
Ref: https://wpewebkit.org/release/wpewebkit-2.34.4.html
```

webkitgtk,wpewebkit: bump to version 2.34.4

---

recipes-browser/webkitgtk/webkitgtk_2.34.5.bb
recipes-browser/wpewebkit/wpewebkit_2.34.5.bb

Release notes:
* Improve VP8 codec selection when using GStreamer 1.20.
* Fix connecting to the accessibility bus when using the Bubblewrap sandbox.
* Fix links being incorrectly activated when starting a pinch zoom gesture.
* Fix touch-based scrolling.
* Fix the build with recent toolchains based on GCC 12 and on older ones as included e.g. in Ubuntu 18.04.
* Fix the build with ICU 60, version 61 is no longer required.

Bump up wpewebkit,webkitgtk to version 2.34.5

---

recipes-browser/webkitgtk/webkitgtk_2.34.5.bb
recipes-browser/wpewebkit/wpewebkit_2.34.5.bb

Release notes:
* Improve VP8 codec selection when using GStreamer 1.20.
* Fix connecting to the accessibility bus when using the Bubblewrap sandbox.
* Fix links being incorrectly activated when starting a pinch zoom gesture.
* Fix touch-based scrolling.
* Fix the build with recent toolchains based on GCC 12 and on older ones as included e.g. in Ubuntu 18.04.
* Fix the build with ICU 60, version 61 is no longer required.

[backport] Bump up wpewebkit,webkitgtk to version 2.34.5

---

recipes-browser/webkitgtk/webkitgtk_2.34.6.bb
recipes-browser/wpewebkit/wpewebkit_2.34.6.bb

This is a bug fix release in the stable 2.34 series.
Release notes:
* Fix accessibility not working when the Bubblewrap sandbox is enabled.
* Fix the build in a number of situations where the main OpenGL library
is not called libGL or libgl, as is the case on systems that use
libglvnd.
Ref: https://wpewebkit.org/release/wpewebkit-2.34.6.html

wpewebkit,webkitgtk: bump to version 2.34.6

---

recipes-browser/cog/cog_0.12.2.bb

Release notes: https://wpewebkit.org/release/cog-0.12.2.html

cog: bump to version 0.12.2

---

recipes-browser/cog/cog_0.12.2.bb

Release notes: https://wpewebkit.org/release/cog-0.12.2.html

[backport] cog: bump to version 0.12.2

---

recipes-browser/cog/cog_0.12.3.bb

Release notes: https://wpewebkit.org/release/cog-0.12.3.html

cog: bump to version 0.12.3

---

recipes-browser/cog/cog_0.12.3.bb

Release notes: https://wpewebkit.org/release/cog-0.12.3.html

[backport] cog: bump to version 0.12.3

---

recipes-browser/wpewebkit/wpewebkit/0001-WPE-Build-ANGLE-with-the-EGL_NO_PLATFORM_SPECIFIC_TY.patch
recipes-browser/wpewebkit/wpewebkit_2.34.7.bb
recipes-browser/wpewebkit/wpewebkit_2.36.0.bb

```
commit 77088643c1ba85da4dc08f53f5eda167cea9b52c (HEAD -> psaavedra/fixes, origin/psaavedra/fixes)
Author: Pablo Saavedra <psaavedra@igalia.com>
Date:   Mon Apr 11 11:27:44 2022 +0200
wpewebkit: Fix build WPE no X11 headers present
Upstream-Status: Submitted [https://bugs.webkit.org/show_bug.cgi?id=239039]
commit 8123c76442a161ede5770efc1b7575c37905e64a
Author: Pablo Saavedra <psaavedra@igalia.com>
Date:   Mon Apr 11 11:13:22 2022 +0200
wpewebkit: Bump up version to 2.34.7
* Release notes: https://wpewebkit.org/release/wpewebkit-2.34.7.html
```

wpewebkit: bump version to 2.34.7

---

recipes-browser/webkitgtk/webkitgtk/webkitgtk-0001-GTK-WPE-Build-ANGLE-with-the-EGL_NO_PLATFORM_SPECIFI.patch
recipes-browser/webkitgtk/webkitgtk_2.36.2.bb
recipes-browser/wpewebkit/wpewebkit_2.36.2.bb

wpewebkit:
* Fix some pages showing empty content boxes when using threaded rendering.
* Fix the build with accessibility disabled.
* Fix the build with newer Ruby versions.
* Release notes: https://wpewebkit.org/release/wpewebkit-2.36.2.html
webkitgtk:
* Fix some pages showing empty content boxes when using GTK4.
* Fix the build with accessibility disabled.
* Fix the build with newer Ruby versions.
* Release notes: https://webkitgtk.org/2022/05/18/webkitgtk2.36.2-released.html

wpewebkit,webkitgtk: Bump up version to 2.36.2

---

recipes-browser/wpewebkit/wpewebkit.inc

Otherwise libsystemd might or might not be available, depending on other
PACKAGECONFIG options that might add it implicitly.
(cherry picked from commit 3eec26f6ee36a0397aff0848b1980697f5e1de83)
Signed-off-by: Bastian Krause <bst@pengutronix.de>
Signed-off-by: Joshua Watt <Joshua.Watt@garmin.com>

wpewebkit: add systemd build dependency for PACKAGECONFIG[systemd] (backport for Dunfell)

---

recipes-browser/wpewebkit/wpewebkit/0001-Fix-include-path-gstreamer-on-cross-toolchain.patch
recipes-browser/wpewebkit/wpewebkit_2.36.3.bb

Upstream issue: https://bugs.webkit.org/show_bug.cgi?id=241483 - https://github.com/WebKit/WebKit/pull/1428

wpewebkit: Fix include gstreamer path on cross compiler toolchains 

---

recipes-browser/wpewebkit/wpewebkit.inc

This commit fixes this warning for the compatible releases to this
branch previous to kirkstone:
```
WARNING: wpewebkit-2.36.3-r0 do_populate_lic: wpewebkit: No generic license file exists for: LGPL-2.0-or-later in any provider
WARNING: do_rootfs: The license listed LGPL-2.0-or-later was not in the licenses collected for recipe wpewebkit
```
The LGPL-2.0-or-later license was added for Poky(kirkstone) in:
```
commit 2456f523cfbbae0e509797a0aefa9733f2cb13e3
Author: Meh Mbeh Ida Delphine <idadelm@gmail.com>
Date:   Thu Oct 15 21:45:39 2020 +0100
licenses: Update license file to match current SPDX names
```
Unreviewed change

wpewebkit: Fix license warnings for Yocto releases previous to kirkstone

---

recipes-graphics/libjxl/libjxl.inc

The CMake build system of libjxl relies on `pkg-config` to find the system `libhwl`. Inherit the `pkgconfig` class on the recipe.
This fixes the following build error:
```
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 11.3.0
| -- The CXX compiler identification is GNU 11.3.0
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Check for working C compiler: /home/clopez/yocto/build-rpi3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/libjxl/0.6.1-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc - skipped
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Check for working …
```

libjxl needs pkg-config to find libhwy (highway)

---

recipes-browser/webkitgtk/webkitgtk_2.36.4.bb
recipes-browser/wpewebkit/wpewebkit_2.36.4.bb

* Fix the new ATSPI accessibility implementation to add the missing
Collection interface for the loaded document.
* Fix the MediaSession implementation to make the MPRIS object names more
sandbox friendly, which plays better with Flatpak and WebKit’s own
Bubblwrap-based sandboxing.
* Fix leaked Web Processes in some particular situations.
* Fix the build with media capture support enabled.
* Fix cross-compilation when targeting 64-bit ARM.

wpewebkit,webkitgtk: Bump up version to 2.36.4

---

recipes-browser/webkitgtk/webkitgtk_2.36.6.bb
recipes-browser/wpewebkit/wpewebkit_2.36.6.bb

From 2.36.5:
* Add support for PAC proxy in the WebDriver implementation.
* Fix video playback when loaded through custom URIs, this fixes
video playback in the Yelp documentation browser.
* Fix WebKitWebView::context-menu when using GTK4.
* Fix LTO builds with GCC.
From 2.35.6:
* Fix handling of touchpad scrolling on GTK4 builds.
* Fix WebKitGTK not allowing to be used from non-main threads.

wpewebkit,webkitgtk: Bump up version to 2.36.6

---

recipes-browser/wpewebkit/wpewebkit_2.36.7.bb

This was changed a while ago, the old repo URL is frozen in time and we need newer sources for devupstream now.
Also remove the current SRCDEV commit pointing to an old branch, leaving it as comment because it's likely to be used in the future.
Thanks @aperezdc for the pointers.

Change devupstream repo to the current location

---

recipes-browser/wpewebkit/wpewebkit_2.38.0.bb

This allows to build WPE with support for the new Layer-Based SVG engine.

Add 'lbse' packageconfig option WPE 2.38.

---

recipes-browser/wpewebkit/wpewebkit_2.38.2.bb

* wpewebkit: Add unifdef-native dependency for versions >2.38
* devupstream: Honors DEPENDS:class-devupstream
Fixes: #416

wpewebkit: Add unifdef-native dependency for versions >2.38

---

recipes-devtools/dicts/test-dicts_git.bb
recipes-devtools/fonts/webkit-test-fonts_git.bb

The WebKit test tooling expects to find this helper files in `/usr/share` instead of in the rootfs. This is the path where those are installed also on the FlatPak SDK.
Reference: see `getFontsPath()` in source files `ActivateFontsGtk.cpp` and `ActivateFontsWPE.cpp` inside directory 'Tools' of WebKit as well as recipes for BuildStream `webkitgtk-test-dicts.bst` and `webkitgtk-test-fonts.bst` also inside on the 'Tools' directory of WebKit

Install webkit test-fonts and test-dicts in /usr/share

---

recipes-browser/wpebackend-rdk/wpebackend-rdk.inc
recipes-browser/wpebackend-rdk/wpebackend-rdk_1.20221201.bb

* Update recipe to the last version
* Move some dependencies related to input handling to be unconditional. The build will fail without them.
* Remove cmake options that not longer exist like `USE_KEY_INPUT_HANDLING_LINUX_INPUT`
* Simply the options for the backends: all of them are disabled by default, so we only have to enable the cmake option if selected.

wpebackend-rdk: Update to last version and update packageconfig entries

---

recipes-browser/webkitgtk/webkitgtk_2.38.3.bb
recipes-browser/wpewebkit/wpewebkit_2.38.3.bb

* Fix runtime critical warnings from media player.
* Fix network process crash when fetching website data on ephemeral session.
* Fix the build with Ruby 3.2.

webkitgtk,wpewebkit: Version bump up to 2.38.3

---

recipes-multimedia/webm/libvpx_1.10.0.bb

as this is mandatory for a while now and removes a warning from the build log

libvpx: add branch info to fetcher

---

recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bb

* sparkle-cdm recipe is provided by this layer (meta-webkit) and is needed to build WPE with ENABLE_THUNDER, which gets enabled by default when ENABLE_DEVELOPER_MODE is set.
* This allows to build WPE with some basic EME support at runtime, including clearkey layout tests coverage support.
This was suggested by @philn  at https://github.com/WebKit/WebKit/pull/7885#discussion_r1086482682

Add sparkle-cdm and flite to packagegroup-wpewebkit-depends-alternative

---

recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bb

On commit 5019d001d4a8fabba88800645bd7814f57764198 this dependency was added, but this is not available before langdale, so add it conditionally based on the Yocto release.
Thanks @psaavedra for the fix.

Add flite dependency only on 'langdale' and newer

---

recipes-browser/libwpe/libwpe_1.14.1.bb
recipes-browser/webkitgtk/webkitgtk_2.38.4.bb
recipes-browser/wpewebkit/wpewebkit_2.38.4.bb

... and also libwpe to 1.14.1
* Release notes:
* https://webkitgtk.org/2023/02/02/webkitgtk2.38.4-released.html
* https://wpewebkit.org/release/wpewebkit-2.38.4.html
* https://wpewebkit.org/release/libwpe-1.14.1.html

wpewebkit,webkitgtk: Bump up version to 2.38.4     

---

recipes-browser/webkitgtk/webkitgtk_2.32.1.bb

NOTE: This is PR for old dunfell branch (not main)
Fixes build when systemd or gamepad is not used
(cherry-picked from commit 059a7ae56e6cd74860ee5e7e49bd0114c25c3743)
Fixes #452

webkitgtk: Add packageconfigs for gamepad and systemd (Fixes #452)

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_1.14.0.bb
recipes-browser/wpebackend-fdo/wpebackend-fdo_1.14.1.bb
recipes-browser/wpebackend-fdo/wpebackend-fdo_devupstream.bb

This version contains important correctness fixes. Release notes:
https://wpewebkit.org/release/wpebackend-fdo-1.14.1.html

wpebackend-fdo: Bump to version 1.14.1

---

recipes-browser/cog/cog-meson.inc

Also:
* graphene: disable neon support on arm 32bits (https://github.com/ebassi/graphene/issues/215). Upstream-status: [Reported](https://lists.openembedded.org/g/openembedded-devel/message/100996)

cog: Fix wrong var in use to add the selected platforms

---

recipes-browser/wpewebkit/wpewebkit.inc

Hi,
when i build wpewebkit and cog for loongarch architecture, it will report `ENABLE_JIT conflicts with ENABLE_C_LOOP.  You must disable one or the other.` error, so loongarch64 JIT is not supported, remove it in wpewebkit.inc.

loongarch64 JIT is not supported, remove it in wpewebkit.inc

---

recipes-browser/cog/cog_0.17.90.bb

* drm: Properly support input-less setups and situations in which the
initialization of the XKB context may have failed.
* x11, wl: Make mouse scroll wheel behaviour snappier.
* launcher: Support passing the platform plug-in name and its parameters
using environment variable
* webkit-utils: Check if the media engine will show the resource
cog_handle_web_view_load_failed() checks if the error is
WEBKIT_MEDIA_ERROR or WEBKIT_MEDIA_ERROR_WILL_HANDLE_LOAD and relies
on WebKit in these cases.
Similarly it does the same for the case of WPE API previous to 2.0
but using WEBKIT_PLUGIN_ERROR and WEBKIT_PLUGIN_ERROR_WILL_HANDLE_LOAD
Upstream-Status: **Accepted** [[cog!569](https://github.com/Igalia/cog/pull/569/)]

cog: Bump-up version to 0.17.90

---

recipes-browser/wpewebkit/wpewebkit/0001-FELightningNEON.cpp-fails-to-build-NEON-fast-path-se.patch

* Since Yocto 4.2 Mickledore a patch applying with fuzz is a fatal error
* Update the patch to not apply with fuzz and also include the upstream-status label
See #471

Update FELightningNEON.cpp-fails-to-build-NEON patch to not apply with fuzz in 2.40.1

---

recipes-browser/wpewebkit/wpewebkit/0001-WPE-Fix-build-without-USE_GBM.patch
recipes-browser/wpewebkit/wpewebkit_2.40.5.bb

This Pull Request addresses two primary issues to enhance WPEWebkit support on the IMX6 platform:
1. **Add patch to fix cmake for wpewebkit**: Introduces a new patch that modifies the cmake file for WPEWebkit. This allows for the compilation without the `USE_GBM` macro, which is otherwise declared by default inside the cmake and cannot be disabled during compilation. The patch is located at `recipes-browser/wpewebkit/wpewebkit/0001-WPE-Fix-build-without-USE_GBM.patch`.
2. **Update WPEWebkit Recipe to Version 2.40.5**: This updates WPEWebkit from version 2.40.3 to 2.40.5, incorporating the latest features and bug fixes.
- Enables the ability to compile WPEWebkit without the `USE_GBM` macro, which is declared inside the cmake and prevents its deactivation during the build.
- Keeps WPEWebkit …

Update and Fix WPEWebkit Compilation

---

conf/templates/template/bblayers/bblayers.conf.layers
recipes-browser/wpewebkit/wpewebkit.inc

... as it is in WPE WebKit by default since 2.40.
Also, added an additional commit for removing an deprecated WebKit config flag (`WEBGL2`).

wpewebkit: Set mediastream flag enabled

---

recipes-browser/cog/cog/0002-wl-Do-not-attach-frames-with-invalid-size-to-the-sur.patch
recipes-browser/cog/cog_0.14.1.bb

When launching cog in Weston kiosk mode on a board with a display resolution of 1024 x 600, the following error is seen:
xdg_wm_base@10: error 4: xdg_surface geometry (1024 x 768) is larger than the configured fullscreen state (1024 x 600)
Fix it by backporting an upstream cog commit so that it can be launched successfully.

cog: Fix the launch in Weston kiosk mode

---

conf/distro/webkitdevci.conf

When using meta-webkit with scarthgap branch, the build fails, complaining about the missing 'usrmerge' DISTRO_FEATURE -- enable it to fix builds with newer Yocto releases.

Fix build failure on scarthgap.

---

recipes-browser/wpewebkit/wpewebkit.inc

Add a new PACKAGECONFIG option to allow building a WebKit release build including debug information (CMAKE_BUILD_TYPE=RelWithDebInfo).

wpewebkit: Add a "release-with-debug-info" knob.

---

recipes-browser/wpewebkit/wpewebkit_2.44.4.bb

Changes:
* Add quirk to allow totale.rosettastone.com to load properly.
* Decrease input notifications for gamepad inputs.
* Disable the gst-libav AAC decoder.
* Make gamepads visible on axis movements, and not only on button presses.
* Make user scripts and style sheets visible in the Web Inspector.
* Undeprecate console message API and make it available in 2022 API.
* Use optimized assembler BoringSSL modules with USE_LIBWEBRTC enabled.
* Use the geolocation portal where available, with the existing Geoclue as fallback if the portal is not usable.
* Fix accelerated images dissapearing after scrolling.
* Fix mouse location in WebDriver when output device scaling is in effect.
* Fix not being able to jump-to-source in Web Inspector canvas traces.
* Fix not being able to scroll list of …

wpewebkit: Bump to version 2.44.4

---

recipes-browser/webkitgtk/webkitgtk_2.44.4.bb

Changes:
* Add quirk to allow totale.rosettastone.com to load properly.
* Decrease input notifications for gamepad inputs.
* Disable the gst-libav AAC decoder.
* Make gamepads visible on axis movements, and not only on button presses.
* Make user scripts and style sheets visible in the Web Inspector.
* Undeprecate console message API and make it available in 2022 API.
* Use optimized assembler BoringSSL modules with USE_LIBWEBRTC enabled.
* Use the geolocation portal where available, with the existing Geoclue as fallback if the portal is not usable.
* Fix accelerated images dissapearing after scrolling.
* Fix mouse location in WebDriver when output device scaling is in effect.
* Fix not being able to jump-to-source in Web Inspector canvas traces.
* Fix not being able to scroll list of …

webkitgtk: Bump to version 2.44.4

---

recipes-browser/wpewebkit/wpewebkit.inc

otherwise setting REQUIRED_DISTRO_FEATURES has no effect. Fixes build warning;
wpewebkit-2.46.1-r0 do_package_qa: QA Issue: wpewebkit: recipe doesn't inherit features_check [unhandled-features-check]

wpewebkit: inherit feature_check

---

.github/manifest/manifest-styhead.xml
.github/workflows/test-build.yml
conf/layer.conf
recipes-extended/highway/files/pr_1589.patch

Add compatible Styhead Yocto release. These changes introduce support for the a `manifest-styhead.xml` in the `.github/manifest/` directory and update the GitHub Actions workflow to include build steps for the Styhead release.

Add Support for Styhead Release 

---

recipes-browser/wpewebkit/wpewebkit/0005-WPEPlatform-Input-methods-do-not-work.patch
recipes-browser/wpewebkit/wpewebkit_2.46.2.bb

Added a new patch `0005-WPEPlatform-Input-methods-do-not-work.patch` to address the missing implementation of `synthesizeCompositionKeyPress()` in WPE Platform.
This patch resolves input method issues described in [Bug 279930](https://bugs.webkit.org/show_bug.cgi?id=279930).
Upstream-Status: Backport [https://commits.webkit.org/284155@main]

wpewebkit: Implement synthesizeCompositionKeyPress() for WPE Platform

---

conf/layer.conf
recipes-browser/webkitgtk/webkitgtk/0001-Build-fixes-for-gbm-disabled-and-release-logs-disabl.patch
recipes-browser/webkitgtk/webkitgtk_2.46.4.bb
recipes-browser/wpewebkit/wpewebkit/0006-WPE-GTK-Build-fixes-for-gbm-disabled-and-release-log.patch
recipes-browser/wpewebkit/wpewebkit/0007-Unreviewed-reverting-292-webkitglib-2.46-cdbaf316924.patch
recipes-browser/wpewebkit/wpewebkit_2.46.4.bb

WebKitGTK changes:
* Improve memory consumption and performance of Canvas getImageData.
* Fix preserve-3D intersection rendering.
* Fix video dimensions since GStreamer 1.24.9.
* Fix the HTTP-based remote Web Inspector not loading in Chromium.
* Fix content filters not working on about:blank iframes.
WPEWebKit 2.46.4 Changes:
* Improve memory consumption and performance of Canvas getImageData().
* Improve reliability and latency of audio/video MediaStream pipeplines.
* Improve detection of accelerated H.264 decoders.
* Add WebM audio capture bitrate configuration with GStreamer 1.24.9 and newer.
* Fix multi-touch input event handling.
* Fix getDisplayMedia() buffer format negotiation with PipeWire.
* Fix wrong video dimensions with GStreamer …

wpewebkit, webkitgtk: Bump to version 2.46.4

---

recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bb

acceptance properly for openh264 and gstreamer1.0-libav. For both LICENSE_FLAGS_ACCEPTED needs to
contain "commercial" to use it

wepwebkit-depends: check commercial license

---

conf/layer.conf
dynamic-layers/webserver/recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bbappend
dynamic-layers/webserver/recipes-core/images/webkit-dev-ci-tools.bbappend
recipes-browser/images/webkit-dev-ci-tools.bb
recipes-browser/packagegroups/packagegroup-wpewebkit-depends.bb

as apache2 and apache2-scripts are served out of meta-webserver, it is better to move them to a dynamic layer setup, then making the layer mandatory, when only a few users are affected by this

layer: move meta-webserver parts to dynamic layer

---

recipes-browser/images/webkit-dev-ci-tools.bb
recipes-browser/webkitgtk/webkitgtk/0001-Build-fixes-for-gbm-disabled-and-release-logs-disabl.patch
recipes-browser/webkitgtk/webkitgtk_2.46.4.bb
recipes-browser/wpewebkit/wpewebkit/0005-WPEPlatform-Input-methods-do-not-work.patch
recipes-browser/wpewebkit/wpewebkit/0006-WPE-GTK-Build-fixes-for-gbm-disabled-and-release-log.patch
recipes-browser/wpewebkit/wpewebkit/0007-Unreviewed-reverting-292-webkitglib-2.46-cdbaf316924.patch
recipes-browser/wpewebkit/wpewebkit_2.46.2.bb
recipes-browser/wpewebkit/wpewebkit_2.46.4.bb

This PR backports multiple changes and improvements to WebKitGTK and WPEWebKit, aligning them with version 2.46.4. Key updates include:
1. **WebKitGTK:**
- Version bump to 2.46.4.
- Enhancements:
- Improved memory consumption and Canvas performance.
- Fixed rendering and video dimension issues with GStreamer 1.24.9.
- Resolved issues with the remote Web Inspector and content filters.
- Addressed crashes and rendering bugs.
- Backported patches:
- Build fixes for GBM and release logs disabled.
- Additional fixes for specific regressions and upstream consistency.
2. **WPEWebKit:**
- Version bump to 2.46.4.
- Enhancements:
- Improved MediaStream pipeline performance.
- Added WebM bitrate configuration for GStreamer 1.24.9.
- Fixed multi-touch events and buffer negotiation for PipeWire.
- …

[scarthgap] Backport Updates for WebKitGTK and WPEWebKit 2.46.4

---

.github/actions/bitbake-build/action.yml

Introduced a retry mechanism with a maximum of 5 attempts to fetch sources during the BitBake process.

ci: Add retry mechanism for fetching sources in bitbake-build

---

recipes-browser/webkitgtk/webkitgtk_2.46.6.bb
recipes-browser/wpewebkit/wpewebkit_2.46.6.bb

* Support building against ICU 76.1
* Fix lost initial audio samples played using WebAudio on 32-bit Raspberry Pi devices when using the OpenMAX GStreamer elements.
* Fix rendering on GPUs with maximum texture size smaller than 2000x2000 pixels by querying the maximum size supported at runtime.
* Fix a crash when enabling Skia CPU rendering.

webkitgtk,wpewebkit: Bump to version 2.46.6

---

recipes-browser/webkitgtk/webkitgtk_2.46.6.bb
recipes-browser/wpewebkit/wpewebkit_2.46.6.bb

* Support building against ICU 76.1
* Fix lost initial audio samples played using WebAudio on 32-bit Raspberry Pi devices when using the OpenMAX GStreamer elements.
* Fix rendering on GPUs with maximum texture size smaller than 2000x2000 pixels by querying the maximum size supported at runtime.
* Fix a crash when enabling Skia CPU rendering.

[backport][scarthgap] webkitgtk,wpewebkit: Bump to version 2.46.6

---

.github/actions/bitbake-build/action.yml
.github/actions/bitbake-repo/action.yml
.github/workflows/test-build.yml

* Added steps to clean the build directory and download artifacts in `bitbake-build/action.yml`.
* Added artifact upload functionality in `bitbake-repo/action.yml`.
* Changed runner environment from `self-hosted` to `ubuntu-22.04` in `test-build.yml` for consistency and reliability.
* Installed necessary packages (`git`, `git-lfs`, `repo`) in `bitbake-repo/action.yml` to ensure environment readiness.

ci: Enhance GitHub Actions for Bitbake Build and Repo

---

recipes-multimedia/dav1d/dav1d.inc
recipes-multimedia/dav1d/dav1d/CVE-2024-1580.patch

Adds patch for CVE-2024-1580 which affects dav1d 0.9.1.

dav1d: Fix CVE-2024-1580

---

README.md

* Added `layers` information for `openembedded-core` and `meta-openembedded` in the README.
* Specified `meta` for `openembedded-core` and `meta-multimedia, meta-oe, meta-python` for `meta-openembedded`.
Issue: https://github.com/Igalia/meta-webkit/issues/536

Update README with additional layer dependencies

---

recipes-graphics/wpe-testbed_git.bb

Introduced the recipe `wpe-testbed_git.bb` under `recipes-graphics` for the WPE Testbed Application.

wpe-testbed: Add recipe to the layer

---

recipes-devtools/qemu/qemu-native/0001-linux-user-Guard-RESOLVE_CACHED-flag-with-preprocess.patch
recipes-devtools/qemu/qemu-native_%.bbappend

* Include patch for QEMU 9.2.x or higher (>=walnascar) to apply compatibility patch
* Prevents build errors when RESOLVE_CACHED is undefined in headers

qemu-native: Add patch to guard RESOLVE_CACHED flag in linux-user

---

recipes-browser/wpebackend-fdo/wpebackend-fdo_1.14.4.bb
recipes-browser/wpewebkit/wpewebkit_2.46.7.bb

This PR brings two upstream version bumps and related fixes to scarthgap:
* **wpebackend-fdo:** bump to 1.14.4
* fix build with GCC 15
* update release notes URL to [https://wpewebkit.org/release/wpebackend-fdo-1.14.4.html](https://wpewebkit.org/release/wpebackend-fdo-1.14.4.html)
* **wpewebkit:** update to version 2.46.7
* rename recipe from `wpewebkit_2.46.6.bb` to `wpewebkit_2.46.7.bb`
* update tarball SHA256 checksum
* fix build when `USE_GSTREAMER_GL` is disabled
* address several crashes and rendering issues
Partial backport of https://github.com/Igalia/meta-webkit/pull/545

wpebackend-fdo: bump to 1.14.4 and wpewebkit: update to 2.46.7

---

recipes-browser/wpewebkit/wpewebkit/0001-Enforce-surface-size-match-when-maximized-to-avoid-W.patch
recipes-browser/wpewebkit/wpewebkit_2.48.1.bb

Add patch to skip rendering buffers with size mismatch in maximized state. This prevents Wayland XDGprotocol error: invalid_surface_state
Upstream-Status: Backport [https://bugs.webkit.org/show_bug.cgi?id=293172]

wpewebkit: Enforce surface size match when maximized

---

recipes-browser/webkitgtk/webkitgtk_2.48.3.bb
recipes-browser/wpewebkit/wpewebkit_2.48.3.bb

**Description**
This PR brings both WebKitGTK and WPEWebKit up to version 2.48.3.
* **webkitgtk**
* bump version to 2.48.3 in the recipe
* **wpewebkit**
* rename recipe from `wpewebkit_2.48.1.bb` to `wpewebkit_2.48.3.bb`
* update `SRCREV` (devupstream class) to `50eef6579cbe`

webkitgtk,wpewebkit: Update to 2.48.3

---

recipes-browser/wpewebkit/wpewebkit.inc

* Introduce `sysprof` and `system-sysprof` options in `PACKAGECONFIG` to enable Sysprof capture.
* Adjust `EXTRA_OECMAKE` to remove the default disabling of `USE_SYSTEM_SYSPROF_CAPTURE`.
Change-Type: minor

wpewebkit: Add sysprof support
