Igalia/meta-webkit

- recipes-browser/wpebackend-fdo/wpebackend-fdo/removes-unnecessary-include-eglmesaext.patch
- recipes-browser/wpebackend-fdo/wpebackend-fdo_git.bb
Please, review with care, Yocto newbie here.
> Add WPEBackend-fdo to browser recipes

- recipes-browser/wpewebkit/wpewebkit_trunk.bb
This should be configured at the image or machine level.
> wpewebkit: remove gst-omx dependency

- recipes-browser/webkitgtk/webkitgtk_2.22.4.bb
Latest stable version available in the layer currently is 2.20.5
> webkitgtk: add 2.22.4

- recipes-browser/wpewebkit/wpewebkit.inc
> Add new PACKAGECONFIG USE_OPENJPEG (#69)

- recipes-browser/webkitgtk/webkitgtk_2.22.6.bb
- recipes-browser/wpewebkit/wpewebkit_2.22.4.bb
> WSA-2019-0001 vulnerabilities were discovered in WebKitGTK+ and WPE WebKit before 2.22.6 and 2.22.4

- recipes-browser/wpewebkit/wpewebkit_2.22.5.bb
Bump the version of WPE WebKit to 2.22.5.
> [wpe] Bump version to 2.22.5

- recipes-browser/cog/cog_0.4.0.bb
- recipes-browser/libwpe/libwpe_1.4.0.bb
- recipes-browser/wpebackend-fdo/wpebackend-fdo_1.4.0.bb
- recipes-browser/wpewebkit/wpewebkit_2.26.0.bb
* libwpe: add recipe for the 1.4.0 release.
* wpebackend-fdo: add recipe for the 1.4.0 release.
* wpewebkit: add recipe for the 2.26.0 release.
* cog: add recipe for the 0.4.0 release.
> Add recipes for latest release series.

- .gitlab-ci.yml
- conf/layer.conf
- recipes-browser/wpewebkit/wpewebkit_trunk.bb
> Yocto layer compatibility upgraded to zeus

- recipes-browser/wpewebkit/wpewebkit/Do-not-detect-the-stopped-animations.patch
- recipes-browser/wpewebkit/wpewebkit_2.26.4.bb
Patch to solve issue discussed here https://github.com/Igalia/meta-webkit/issues/143
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
> wpewebkit: 2.26.4: Add patch to do not detect the stopped animations

- recipes-browser/cog/cog_0.4.0.bb
- recipes-browser/cog/cog_0.5.1.bb
- recipes-browser/libwpe/libwpe_1.4.0.1.bb
- recipes-browser/libwpe/libwpe_1.6.0.bb
- recipes-browser/wpebackend-fdo/wpebackend-fdo_1.4.1.bb
- recipes-browser/wpebackend-fdo/wpebackend-fdo_1.6.0.bb
- recipes-browser/wpewebkit/wpewebkit_2.26.4.bb
- recipes-browser/wpewebkit/wpewebkit_2.28.0.bb
Update to the most recent release
> cog, libwpe, wpebackend-fdo, wpewebkit: Update to latest release

- conf/layer.conf
> layer.conf: Add dunfell to compatible releases

- recipes-browser/cog/cog/0001-cog-launcher-Move-auto-ptr-declation-before-goto-sta.patch
- recipes-browser/cog/cog_0.5.1.bb
> cog: Fix build with clang

- recipes-browser/wpebackend-fdo/wpebackend-fdo.inc
- recipes-browser/wpebackend-fdo/wpebackend-fdo_1.4.1.bb
- recipes-browser/wpebackend-fdo/wpebackend-fdo_1.6.0.bb
> wpebackend-fdo: Simplification of the DEPENDS definition

- recipes-browser/webkitgtk/webkitgtk_2.28.2.bb
- recipes-browser/wpewebkit/wpewebkit_2.28.2.bb
> Bump up of  webkitgtk and wpewebkit to 2.28.2

- recipes-browser/webkitgtk/webkitgtk_2.28.4.bb
- recipes-browser/wpewebkit/wpewebkit_2.28.4.bb
* wpewebkit: Security update to 2.28.4
- WPE WebKit Advisory URL: https://wpewebkit.org/security/WSA-2020-0007.html
* webkitgtk: Security update to 2.28.4
- WebKitGTK Advisory URL: https://webkitgtk.org/security/WSA-2020-0007.html
> WSA 2020 0007

- conf/layer.conf
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
> conf/layer.conf: Add gatesgarth to LAYERSERIES_COMPAT

- recipes-browser/wpewebkit/wpewebkit/ICU-68.1-no-longer-exposes-FALSE-and-TRUE-macros-by-.patch
- recipes-browser/wpewebkit/wpewebkit_2.30.3.bb
Apply patch to work with ICU 68.1
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
> wpewebkit: Update 2.30.0 -> 2.30.3

- conf/include/webkit-bleeding.inc
> wekbit-bleeding: Update preferred version

- recipes-browser/wpewebkit/wpewebkit_2.30.5.bb
This is a bug fix release in the stable 2.30 series.
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
> wpewebkit: Update 2.30.4 -> 2.30.5

- .gitlab-ci.yml
- .gitlab-ci/manifest/manifest-dunfell.xml
- .gitlab-ci/manifest/manifest-zeus.xml
- .gitlab-ci/template/conf-notes.txt
- conf/layer.conf
... for all the supported layers
Issue: https://github.com/Igalia/meta-webkit/issues/224
> ci: Add tasks to check the build for the latest stable webkit version

- recipes-browser/wpewebkit/wpewebkit/0001-EME-Fix-KeySystem-permission-handling.patch
- recipes-browser/wpewebkit/wpewebkit_2.31.91.bb
The included patch is already lined up for either 2.31.92 or 2.32.0.
> wpewebkit: Bump to 2.31.91

- recipes-browser/wpebackend-fdo/wpebackend-fdo_1.8.2.bb
- recipes-browser/wpewebkit/wpewebkit_2.30.6.bb
* wpewebkit: Bump up version to 2.30.6
* wpebackend-fdo: Bump up version to 1.8.2
> wpewebkit: Bump up version to 2.30.6

- recipes-browser/wpebackend-fdo/wpebackend-fdo.inc
- recipes-browser/wpebackend-fdo/wpebackend-fdo_1.8.3.bb
- recipes-browser/wpebackend-fdo/wpebackend-fdo_devupstream.bb
Fixed UI process getting stuck when navigating across different security origins. This also fixed a small memory leak.
> wpebackend-fdo: Update version to 1.8.3

- recipes-browser/webkitgtk/webkitgtk/0001-ICU-69-deprecates-ubrk_safeClone-in-favor-of-ubrk_cl.patch
- recipes-browser/webkitgtk/webkitgtk/0001-Move-cloneUBreakIterator-declaration-to-IntlWorkarou.patch
- recipes-browser/webkitgtk/webkitgtk_2.32.0.bb
- recipes-browser/wpewebkit/wpewebkit/0001-ICU-69-deprecates-ubrk_safeClone-in-favor-of-ubrk_cl.patch
- recipes-browser/wpewebkit/wpewebkit/0001-Move-cloneUBreakIterator-declaration-to-IntlWorkarou.patch
- recipes-browser/wpewebkit/wpewebkit_2.32.0.bb
These patches are required t fix build with ICU 69
> wpewebkit: Backport ICU 69 support patches

- recipes-browser/webkitgtk/webkitgtk_2.32.0.bb
- recipes-browser/wpewebkit/wpewebkit.inc
Disable it by default, since it depends on nettle which is LGPL-3
> wpewebkit: Make gnutls a packageconfig knob

- recipes-browser/cog/cog/0001-platform-Add-COG_PLATFORM_HEADLESS-cmake-option.patch
- recipes-browser/cog/cog_0.10.0.bb
SSIA
Related-to: https://github.com/Igalia/cog/pull/318
> cog: Add COG_PLATFORM_HEADLESS cmake option

- .gitlab-ci.yml
- .gitlab-ci/template/include/preferred-wpe-2_32.conf
- .gitlab-ci/template/presets/mesa-wpe-2_32.conf
- .gitlab-ci/template/presets/mesa-wpe-qt.conf
- recipes-browser/webkitgtk/webkitgtk_2.32.1.bb
- recipes-browser/wpewebkit/wpewebkit_2.32.1.bb
Carried things over from main branch.
(based on af3f8de6f4338d0943b18b7099d232ef5ea924b7)
> ci: Add 2.32 CI stuff to dunfell branch

- .gitlab-ci.yml
> WIP ci: Add job to test build webkitgtk

- conf/include/devupstream.inc
> devupstream: PN for devupstream checks if it is already defined in the recipe

- recipes-browser/wpebackend-rdk/wpebackend-rdk_1.20200213.bb
Otherwise this triggers a warning from bitbake.
> [FIX] avoid `append` and `+=` on the same line.

- .gitlab-ci.yml
> ci: Add new CI job for raspberry4-64 machine

- recipes-browser/cog/cog.inc
- recipes-browser/cog/cog/0001-Fix-missing-xkbcommon.h-include.patch
- recipes-browser/cog/cog_0.12.4.bb
Upstream: https://github.com/Igalia/cog/issues/449
> cog: Fix missing xkbcommon.h include on cog 0.12.4

- recipes-browser/webkitgtk/webkitgtk_2.36.7.bb
- recipes-browser/wpewebkit/wpewebkit/0001-Merge-253133-main-JSC-Make-JSMap-and-JSSet-construct.patch
- recipes-browser/wpewebkit/wpewebkit_2.34.7.bb
- recipes-browser/wpewebkit/wpewebkit_2.36.7.bb
> wpewebkit,webkitgtk: Bump up version to 2.36.7

- recipes-browser/cog/cog_0.14.1.bb
Required since 0.14: https://github.com/Igalia/cog/commit/48dfac2ba637e223eeea1b289526d0f51e39ab88
> cog: Add dependency with libxkbcommon

- recipes-browser/wpewebkit/wpewebkit.inc
> wpewebkit: Add webgl2 as default in PACKAGECONFIG

- recipes-browser/webkitgtk/webkitgtk_2.38.5.bb
- recipes-browser/wpewebkit/wpewebkit_2.38.5.bb
wpewebkit, webkitgtk: Bump versions to 2.38.5
Release notes:
- https://wpewebkit.org/release/wpewebkit-2.38.5.html
- https://webkitgtk.org/2023/02/15/webkitgtk2.38.5-released.html
> wpewebkit, webkitgtk: Bump versions to 2.38.5

- recipes-browser/webkitgtk/webkitgtk_2.38.6.bb
- recipes-browser/wpewebkit/wpewebkit_2.38.6.bb
* wpewebkit's Release note: https://wpewebkit.org/release/wpewebkit-2.38.6.html
* webkitgtk's Release note: https://webkitgtk.org/2023/04/20/webkitgtk2.38.6-released.html
> webkitgtk,wpewebkit: Bump up version to 2.38.6

- conf/layer.conf
Adds compatibility with Yocto 4.3 (codename nanbield)
> Add nanield compatibility

- recipes-browser/wpewebkit/wpewebkit.inc
> wpewebkit: fix override syntax

- .github/manifest/manifest-walnascar.xml
- .github/workflows/sync-main-current-release.yml
- .github/workflows/test-build.yml
- conf/layer.conf
> Add compatibility with walnascar

- recipes-browser/libwpe/libwpe_1.16.2.bb
Release notes: https://wpewebkit.org/release/libwpe-1.16.2.html
> libwpe: Add recipe for release 1.16.2

- recipes-browser/libwpe/libwpe_1.16.2.bb
Release notes: https://wpewebkit.org/release/libwpe-1.16.2.html
> [backport] libwpe: Add recipe for release 1.16.2
